- name: playbook for setting up backend
  hosts: backend
  become: yes
  tasks: 
    - name: Disable Node.js module
      ansible.builtin.command:
        cmd: dnf module disable nodejs -y
    - name: Enable Node.js module
      ansible.builtin.command:
        cmd: dnf module enable nodejs:20 -y
    - name: Installing nodejs
      ansible.builtin.dnf:
        name: nodejs
        state: present
    - name: Create user 'expense'
      ansible.builtin.user:
        name: expense
        state: present
    - name: Create /app directory
      ansible.builtin.file:
        path: /app
        state: directory
    - name: Download backend.zip
      ansible.builtin.get_url:
        url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zip
        dest: /tmp/backend.zip
        force: no 
    - name: Execute a command in /app directory
      ansible.builtin.command:
          cmd: "unzip /tmp/backend.zip && npm install" # Replace with the command you want to run
      args:
        chdir: /app
    - name: Copy config file to Node.js application
      ansible.builtin.copy:
        src: /home/ec2-user/expense-Ansible/backend.service
        dest: /etc/systemd/system/backend.service
    - name: Start backend service
      ansible.builtin.systemd:
        name: backend
        state: started
    - name: Enable backend service to start on boot
      ansible.builtin.systemd:
        name: backend
        enabled: yes
