- name: configuring backend for expense
  hosts: backend
  become: yes
  tasks:
  - name: disable default nodejs
    ansible.builtin.command:
      cmd: dnf module disable nodejs -y
  - name: disable default nodejs
    ansible.builtin.command:
      cmd: dnf module enable nodejs:20 -y
  - name: installing nodejs
    ansible.builtin.package:
      name: "{{ item }}"
      state: present
    loop:
    - nodejs
    - mysql
  - name: Add the user 'expense' with a specific uid and a primary group of 'admin'
    ansible.builtin.user:
      name: expense
  - name: Create a directory if it does not exist
    ansible.builtin.file:
      path: /app
      state: directory
  - name: Download backend.zip from S3
    ansible.builtin.get_url:
      url: "https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zip"
      dest: "/tmp/backend.zip"
      mode: '0644'
    