- name: playbook  for installing mysqldb 
  hosts: mysql
  become: yes
  vars:
    mysql_root_password: "ExpenseApp@1"
    localhost: 172.31.19.135
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: task for installing mysql
      ansible.builtin.package:
        name: mysql-server
        state: present
    - name: Install PyMySQL (or mysqlclient if preferred)
      ansible.builtin.pip:
        name: PyMySQL  # or mysqlclient
        state: present
        executable: pip3.9
    - name: Enable and start mysqld service
      ansible.builtin.service:
        name: mysqld
        enabled: yes
        state: started

    - name: checking whether root password is set or not
      community.mysql.mysql_info:
        login_user: root
        login_password: "{{mysql_root_password}}"
        login_host: "{{localhost}}"
      ignore_errors: true
      register: mysql_info
    
    - name: checking the error info
      ansible.builtin.debug:
        msg: "{{mysql_info}}"

    - name: setting root password
      ansible.builtin.command:
        cmd: mysql -h "{{localhost}}" -u root -p"{{mysql_root_password}}"