- name: playbook  for installing mysqldb 
  hosts: mysql
  become: yes
  vars:
    mysql_root_password: "ExpenseApp@1"
    localhost: 172.31.19.135
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: task for installing mysql
      ansible.builtin.package:
        name: mysql-server
        state: present
    - name: Install PyMySQL (or mysqlclient if preferred)
      ansible.builtin.pip:
        name: PyMySQL  # or mysqlclient
        state: present
        executable: pip3.9
    - name: Enable and start mysqld service
      ansible.builtin.service:
        name: mysqld
        enabled: yes
        state: started
    - name: Ensure MySQL root password is set
      ansible.builtin.mysql_user:
        name: root
        host: localhost
        password: "{{ mysql_root_password }}"
        login_unix_socket: /var/lib/mysql/mysql.sock
        state: present