# debug_with_python_interpreter.yaml
- hosts: localhost
  gather_facts: no  # Disable default fact gathering
  vars:
    ansible_python_interpreter: /usr/bin/python3  # Specify your Python interpreter path
  tasks:
  - name: Display the Python interpreter path
    ansible.builtin.debug:
      msg: "{{ ansible_python_interpreter }}"

